# Generated by Django 5.2.1 on 2025-06-10 07:29

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_tracking_id', models.CharField(default='', editable=False, max_length=4, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=50)),
                ('location_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on_site', 'On-site')], max_length=50)),
                ('experience_level', models.CharField(choices=[('intern', 'Intern'), ('traineeship', 'Traineeship'), ('entry_level', 'Entry Level'), ('mid_level', 'Mid Level'), ('senior', 'Senior'), ('director', 'Director'), ('executive', 'Executive')], max_length=50)),
                ('no_of_vacancies', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateField(default=jobs.models.thirtY_days_from_now, help_text='Deadline for job application')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('key_responsibilities', models.TextField()),
                ('core_skills', models.JSONField(default=list, help_text='List of skills')),
                ('nice_to_have_skills', models.JSONField(blank=True, default=list, help_text='List of skills', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the job was created')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
