# Generated by Django 5.2.3 on 2025-07-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvert',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Date when the job was created'),
        ),
        migrations.AlterField(
            model_name='jobadvert',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('traineeship', 'Traineeship'), ('entry_level', 'Entry Level'), ('mid_level', 'Mid Level'), ('senior', 'Senior'), ('director', 'Director'), ('executive', 'Executive')], help_text='Experience level required for the job', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobadvert',
            name='nice_to_have_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills'),
        ),
    ]
